/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beautyparlour.dialog;


import beautyparlour.bean.PaymentDoneBeans;
import beautyparlour.bean.SaleBeans;
import beautyparlour.bean.SaleDetailBeans;
import beautyparlour.bean.ServiceBeans;
import beautyparlour.dao.CustomerDao;
import beautyparlour.dao.SaleDao;
import beautyparlour.dao.SaleDetailsDao;
import beautyparlour.dao.ServiceDao;
import beautyparlour.daoImpl.CustomerDaoImpl;
import beautyparlour.daoImpl.SaleDaoImpl;
import beautyparlour.daoImpl.SaleDetailDapImpl;
import beautyparlour.daoImpl.ServiceDaoImpl;
import beautyparlour.frames.SalePage;
import java.awt.Color;
import java.awt.Font;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Vksoni
 */
public class CashNowLaterDialog extends javax.swing.JDialog {

    PaymentDoneBeans ob = null;
    DefaultTableModel tableModelDebtDetails;
//    DebtDetailDao debtDao;
    SaleDao saleDao;
    CustomerDao customerDao;
    SaleDetailsDao saleDetailDao;
    boolean cashGot = false;
    ServiceDao serviceDao;

//    public ArrayList<DebtDetailBeans> debt_details_list;

    /**
     * Creates new form SetingJDialog
     */
    public CashNowLaterDialog(java.awt.Frame parent, boolean modal, int cust_id, String customer_name) {
        super(parent, modal);
        initComponents();
//        debtDao = new DebtDaoImpl();
//        tableModelDebtDetails = (DefaultTableModel) this.jTableDebtDetails.getModel();
//
//        JTableHeader header = this.jTableDebtDetails.getTableHeader();
//        header.setBackground(new Color(0, 204, 0));
//        header.setForeground(new Color(255, 255, 255));
//        header.setFont(new Font("SansSerif", Font.BOLD, 18));
//        this.jLabelCustomerName.setText("Customer name: " + customer_name);
//        showInTable(cust_id);

    }

    public CashNowLaterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }
    String reference="";

    public CashNowLaterDialog(java.awt.Frame parent, boolean modal, PaymentDoneBeans ob) {
        super(parent, modal);
        initComponents();

        cashGot = true;
        this.ob = ob;
//        this.reference=reference;
        System.out.println("" + ob.getTotal_price());
        pricetoPayField.setText("Total Price To Pay:  " + ob.getTotal_price());
        payNowField.setText(ob.getTotal_price() + "");
        payLaterField.setText("0");
        saleDao = new SaleDaoImpl();
        saleDetailDao = new SaleDetailDapImpl();
        serviceDao = new ServiceDaoImpl();
//        debtDao = new DebtDaoImpl();
        customerDao = new CustomerDaoImpl();
        payLaterField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCustomerName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pricetoPayField = new javax.swing.JLabel();
        payLaterField = new javax.swing.JTextField();
        payNowField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCustomerName.setBackground(new java.awt.Color(102, 204, 255));
        jLabelCustomerName.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustomerName.setText("Payment");
        jLabelCustomerName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true));
        jLabelCustomerName.setOpaque(true);
        jPanel1.add(jLabelCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All rights reserved @Kashtkarzarai|2018");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 2, true));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 500, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Payment Later:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, 20));

        pricetoPayField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pricetoPayField.setText("Total Price To Pay:  ");
        jPanel1.add(pricetoPayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 200, 20));

        payLaterField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(payLaterField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 200, -1));

        payNowField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payNowField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                payNowFieldKeyReleased(evt);
            }
        });
        jPanel1.add(payNowField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Payment Now:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Generate Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

//                    saleDao.saveSale(new SaleBeans(1, customer_id, 1, discount_type, (int) discount, total_price));

        int i=JOptionPane.showConfirmDialog(this, "Are you sure ?");
        
       double paid=Double.parseDouble(this.payNowField.getText());
        if(i==0){

      
//       saleDao.saveSale(new SaleBeans(1, ob.getCustomer_id(), 1,  ob.getDiscount_type(), ob.getDiscount(), ob.getTotal_price(),paid , reference));
    
        LocalDate date = LocalDate.now();
        

        saleDao.saveSale(new SaleBeans(1, ob.getCustomer_id(), 1, ob.getDiscount_type(), 
        ob.getDiscount(), ob.getTotal_price(), paid,date+""));
        
        for (ServiceBeans s : ob.getSelected_service_list()) {
            
                int sale_id = saleDao.getSaleId();

//                saleDetailDao.saveSaleDetails(new SaleDetailBeans(1, sale_id,ob.getCustomer_id(), product_id, quantity, p.getCompany_id(), p.getUom(), ob.getDate() + "", p.getCost()));
            
                saleDetailDao.saveSaleDetails(new SaleDetailBeans(1, sale_id, ob.getCustomer_id(), 
                        s.getService_id(), ob.getDate(), s.getService_cost()));
        }

        

        
        double pay_now = Double.parseDouble(payNowField.getText().toString());
        double pay_later = Double.parseDouble(payLaterField.getText().toString());

        double puranadebt = customerDao.getCustomerDebtByCustomerId(ob.getCustomer_id());
        customerDao.modifyCustomerDebt(ob.getCustomer_id(), pay_later + puranadebt);
        
        this.dispose();
        new  SalePage().setVisible(true);
              
        
        }
        else{
        
        
            
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void payNowFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payNowFieldKeyReleased
        // TODO add your handling code here:
        try {
            if (payNowField.equals("")) {
                payLaterField.setText(ob.getTotal_price() + "");

            } else {
                try {

                    double pay_now = Double.parseDouble(payNowField.getText().toString());
                    if (pay_now > ob.getTotal_price()) {
                        JOptionPane.showMessageDialog(this, "Invalid Amount");
                    } else {
                        payLaterField.setText((ob.getTotal_price() - pay_now) + "");
                    }
                } catch (Exception e) {
                    payLaterField.setText(ob.getTotal_price() + "");
                }
            }
        } catch (Exception e) {
            payLaterField.setText(ob.getTotal_price() + "");
        }

    }//GEN-LAST:event_payNowFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashNowLaterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashNowLaterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashNowLaterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashNowLaterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CashNowLaterDialog dialog = new CashNowLaterDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

//    public void showInTable(int cust_id) {
//        tableModelDebtDetails.setRowCount(0);
//        int i = 1;
//        debt_details_list = debtDao.getAllDetailByCustomerId(cust_id);
//        for (DebtDetailBeans debt : debt_details_list) {
//            Vector V = new Vector();
//            V.add(i++);
//            V.add(debt.getName());
//            V.add(debt.getDebt_amount());
//            V.add(debt.getDate());
//
//            tableModelDebtDetails.addRow(V);
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCustomerName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField payLaterField;
    private javax.swing.JTextField payNowField;
    private javax.swing.JLabel pricetoPayField;
    // End of variables declaration//GEN-END:variables
}
