/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package kashtkarzarai.dialog;
package beautyparlour.dialog;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
//import kashtkarzarai.bean.CustomerBeans;
//import kashtkarzarai.bean.DebtDetailBeans;
//import kashtkarzarai.bean.UOMBeans;
//import kashtkarzarai.dao.DebtDetailDao;
//import kashtkarzarai.dao.UomDao;
//import kashtkarzarai.daoImpl.DebtDaoImpl;
//import kashtkarzarai.daoImpl.UomDaoImpl;

/**
 *
 * @author Vksoni
 */
public class DebtDetailJDialog extends javax.swing.JDialog {

//    DefaultTableModel tableModelDebtDetails;
//    DebtDetailDao debtDao;
//    public ArrayList<DebtDetailBeans> debt_details_list;

    /**
     * Creates new form SetingJDialog
     */
    public DebtDetailJDialog(java.awt.Frame parent, boolean modal, int cust_id, String customer_name) {
        super(parent, modal);
        initComponents();
//        debtDao = new DebtDaoImpl();
//        tableModelDebtDetails = (DefaultTableModel) this.jTableDebtDetails.getModel();

        JTableHeader header = this.jTableDebtDetails.getTableHeader();
        header.setBackground(new Color(0, 204, 0));
        header.setForeground(new Color(255, 255, 255));
        header.setFont(new Font("SansSerif", Font.BOLD, 18));
        this.jLabelCustomerName.setText("Customer name: " + customer_name);
        showInTable(cust_id);

    }

    public DebtDetailJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        debtDao = new DebtDaoImpl();
//        tableModelDebtDetails = (DefaultTableModel) this.jTableDebtDetails.getModel();

        JTableHeader header = this.jTableDebtDetails.getTableHeader();
        header.setBackground(new Color(0, 204, 0));
        header.setForeground(new Color(255, 255, 255));
        header.setFont(new Font("SansSerif", Font.BOLD, 18));
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDebtDetails = new javax.swing.JTable();
        jLabelCustomerName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDebtDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTableDebtDetails.setForeground(new java.awt.Color(0, 0, 51));
        jTableDebtDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr #:", "Debt Submitted by", "Debt Amount", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDebtDetails.setToolTipText("Products");
        jTableDebtDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableDebtDetails.setGridColor(new java.awt.Color(0, 0, 51));
        jTableDebtDetails.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTableDebtDetails.setSelectionForeground(new java.awt.Color(0, 240, 0));
        jTableDebtDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDebtDetailsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableDebtDetails);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 480, 390));

        jLabelCustomerName.setBackground(new java.awt.Color(0, 204, 0));
        jLabelCustomerName.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustomerName.setText("Customer name");
        jLabelCustomerName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true));
        jLabelCustomerName.setOpaque(true);
        jPanel1.add(jLabelCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 50));

        jLabel1.setBackground(new java.awt.Color(0, 204, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All right reserved|2017");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 2, true));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 500, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDebtDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDebtDetailsMouseClicked


    }//GEN-LAST:event_jTableDebtDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DebtDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DebtDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DebtDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DebtDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DebtDetailJDialog dialog = new DebtDetailJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void showInTable(int cust_id) {
//        tableModelDebtDetails.setRowCount(0);
//        int i = 1;
//        debt_details_list = debtDao.getAllDetailByCustomerId(cust_id);
//        for (DebtDetailBeans debt : debt_details_list) {
//            Vector V = new Vector();
//            V.add(i++);
//            V.add(debt.getName());
//            V.add(debt.getDebt_amount());
//            V.add(debt.getDate());
//
//            tableModelDebtDetails.addRow(V);
//        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCustomerName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDebtDetails;
    // End of variables declaration//GEN-END:variables
}
